### ISSUE TITLE
Lamps change color every second when tab is minimized

### ISSUE THREAD

**Issue by DyonR** [hoboman313/huegasm#3]
When using Google Chrome (and maybe other browsers) my lamps only change colors once every second when the Huegasm tab is not the selected tab, or when minimized.
I have tested this in with a local .wav file and Soundcloud, but both have this issue.

**Comment by hoboman313** [comment]
Yes, this is a known issue but it's due to a browser throttling background tabs rather than a bug with huegasm itself. You can read up on it here: https://blog.pivotal.io/labs/labs/chrome-and-firefox-throttle-settimeout-setinterval-in-inactive-tabs

I'll try a few of the workarounds from the article, but I'm skeptical that they'll still work.

**Comment by hoboman313** [comment]
The only thing I can suggest as a workaround is to open huegasm in a separate window instead of tab. Chrome will not throttle it in this case.
